### ISSUE TITLE
What is MM_caching_frequency?

### ISSUE THREAD

**Issue by Jogima-cyber** [NVlabs/DiffRL#14]
Hello, thank you for open-sourcing all this very interesting work. I don't understand what "MM_caching_frequency" is and why it changes throughout the configuration files.

**Comment by eanswer** [comment]
`MM_caching_frequency` defines the frequency to re-compute the mass matrix for physics simulation. It is a common technique in graphics to speed up the simulation. With a small `MM_caching_frequency`, it will update the mass matrix more frequently which results in a more accurate simulation while being more time-consuming, and vice versa.

**Comment by Jogima-cyber** [comment]
Thank you very much, your explanation was perfect!
