### ISSUE TITLE
How to set collision between non-connected  dynamic  bodies?

### ISSUE THREAD

**Issue by MyelinsheathXD** [NVlabs/DiffRL#5]
here on the video , non of the agents have proper collsion between their legs in the default physics engine.
How can I set self collision between  non-connected  dynamic  bodies?

[sample video](https://youtu.be/T63vY8ZCFxo)
https://youtu.be/T63vY8ZCFxo

**Comment by ViktorM** [comment]
Hi @MyelinsheathXD,

Unfortunately, rigid-rigid collisions are not supported by dflex. We'll have them in one of the next releases of Warp. Please check also this thread: https://github.com/NVlabs/DiffRL/issues/2 @mmacklin fyi.
